## Image settings
image:
  name: us-east1-docker.pkg.dev/xstaging-348615/platform/integrations
  tag: latest

imagePullSecrets:
  - gcr-registry

## Quantidade de Replicas
# replicas: 3

## Resources
resources: 
  limits:
   cpu: 100m
   memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60         
         
