{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backoffice.fullname" . }}
  labels:
    app: {{ include "backoffice.name" . }}
    chart: {{ include "backoffice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
    {{- end }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ include "backoffice.name" . }}
    release: {{ .Release.Name }}
{{- end }}
