version: "3"

services:

  redis:
    image: redis:6.2-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data
    networks:
      - integrations-network

networks:
  integrations-network:
    driver: bridge

volumes:
  redis:
