name: Build and Push docker-image on every Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Build Version'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t xgrow/backoffice-nginx.
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run:
          docker tag xgrow/backoffice-nginx registry.digitalocean.com/xgrow-registry/backoffice-nginx-dev:latest
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/xgrow-registry/backoffice-nginx-dev:latest
