# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Trigger the workflow on push event but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'Jonas Diel'
      - run: git config --global user.email 'jonasdiel@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t xgrow/integrations .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Tag image
        run: docker tag xgrow/integrations registry.digitalocean.com/xgrow-registry/integrations:${{ steps.package-version.outputs.current-version}}
      - name: Tag image latest
        run: docker tag xgrow/integrations registry.digitalocean.com/xgrow-registry/integrations:dev-latest
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/xgrow-registry/integrations:${{ steps.package-version.outputs.current-version}}
      - name: Push image latest to DO Container Registry
        run: docker push registry.digitalocean.com/xgrow-registry/integrations:dev-latest
