{{- if .Values.ingress.enabled -}}
{{- $servicePort := .Values.service.port -}}

{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- if $newAPI -}}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}

kind: Ingress
metadata:
  name: {{ include "integration.fullname" . }}
  labels:
    app: {{ include "integration.name" . }}
    chart: {{ include "integration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
    {{- end }}
    {{- if .Values.global }}
{{ toYaml .Values.global.extraLabels | indent 4 }}
    {{- end }}

{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.hosts }}
  - hosts:
      - {{ .host | quote }}
    secretName: {{ .host | replace "." "-" }}-tls
  {{- end }}
  {{- end }}

  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path | quote }}            
            {{- if $newAPI }}
            pathType: Prefix
            backend:               
              service:
                name: {{ template "integration.fullname" $ }}
                port: 
                  number: {{ $servicePort }}
            {{- else }}
            backend:
              serviceName: {{ template "integration.fullname" $ }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- end }}
{{- end }}
