{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "integration.fullname" . }}
  labels:
    {{ include "integration.defaultLabels" . }}
    {{ include "integration.extraLabels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ include "integration.name" . }}
    release: {{ .Release.Name }}
{{- end }}
