version: "3.8"
services:
  checkout-api-nginx:
    container_name: checkout-api-nginx
    build: resources/ops/docker/nginx
    command: nginx -g "daemon off;"
    links:
      - checkout-api
    ports:
      - "${DOCKER_NGINX_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - checkout-api
  checkout-api:
    container_name: checkout-api
    build: resources/ops/docker/php
    volumes:
      - media-files:/var/www/html/storage/app/public
      - .:/var/www/html
    working_dir: /var/www/html
    command: php-fpm
volumes:
  db-data:
  media-files:
