export enum ProposalClass {
  N,
  P
}

export enum ProposalRole {
  LEGAL_REPRESENTATIVE = 'LEGAL_REPRESENTATIVE',
  OWNER = 'OWNER',
  BENEFICIARY = 'BENEFICIARY',
  LEGAL_RESPONSIBLE = 'LEGAL_RESPONSIBLE',
  FINANCIAL_RESPONSIBLE = 'FINANCIAL_RESPONSIBLE'
}
