service: poc-login-leve
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  registerAdmin:
    handler: index.registerAdmin
  
  findUser:
    handler: index.findUser

  register:
    handler: index.register

  confirmUser:
    handler: index.confirmUser

  login:
    handler: index.login

  signOut:
    handler: index.signOut

  forgotPasswordInit:
    handler: index.forgotPasswordInit

  confirmForgotPassword:
    handler: index.confirmForgotPassword

  changePassword:
    handler: index.changePassword
    
  deleteUser:
    handler: index.deleteUser

  loginPasswordless:
    handler: index.loginPasswordless

  userDetails:
    handler: index.userDetails

  loginWithMfa:
    handler: index.loginWithMfa

  respondMfa:
    handler: index.respondMfa

  getUserMfa:
    handler: index.getUserMfa

  resetPassword:
    handler: index.resetPassword

  respondNewPasswordRequired:
    handler: index.respondNewPasswordRequired

  resendCode:
    handler: index.resendCode

