<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class StandardizeCountryField extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'standardize:country_field';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Padronizar campo de País da tabela subscribers';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {

        $this->replaceCountryName();
        $this->replaceCountryCode();
        $this->replaceNonstandardCountryName();
    }

    private function replaceCountryName(){
        $countries = $this->allCountrys();
        foreach($countries as $key => $country){
            DB::table('subscribers')->where('address_country', $country)->update(['address_country' => $key]);
        }
    }

    private function replaceCountryCode(){
        $countries = $this->converCountryCode();
        foreach($countries as $key => $country){
            DB::table('subscribers')->where('address_country', $key)->update(['address_country' => $country]);
        }
    }


    private function replaceNonstandardCountryName(){
        $countries = $this->allNonstandardCountrys();
        foreach($countries as $key => $country){
            foreach($country as $value){
                DB::table('subscribers')->where('address_country', $value)->update(['address_country' => $key]);
            }
        }
    }

    private function allNonstandardCountrys()
    {
        return [
            'ARG' => ['Argentin'],
            'BRA' => ['BRaseul', 'Brazil'],
            'USA' => ['EUA', 'United States'],
            'IRL' => ['Ireland'],
            'JPN' => ['JAPÃO']
        ];
    }


    private function allCountrys()
    {
        return [
            'BRA' => 'Brasil',
            'USA' => 'Estados Unidos',
            'PRT' => 'Portugal',
            'AFG' => 'Afeganistão',
            'ZAF' => 'África do Sul',
            'ALB' => 'Albânia',
            'DEU' => 'Alemanha',
            'AND' => 'Andorra',
            'AGO' => 'Angola',
            'AIA' => 'Anguilla',
            'ATA' => 'Antártida',
            'ATG' => 'Antígua e Barbuda',
            'ANT' => 'Antilhas Holandesas',
            'SAU' => 'Arábia Saudita',
            'DZA' => 'Argélia',
            'ARG' => 'Argentina',
            'ARM' => 'Armênia',
            'AUS' => 'Austrália',
            'AUT' => 'Áustria',
            'AZE' => 'Azerbaijão',
            'BHS' => 'Bahamas',
            'BHR' => 'Bahrein',
            'BGD' => 'Bangladesh',
            'BRB' => 'Barbados',
            'BLR' => 'Belarus',
            'BEL' => 'Bélgica',
            'BLZ' => 'Belize',
            'BEN' => 'Benin',
            'BMU' => 'Bermudas',
            'BOL' => 'Bolívia',
            'BIH' => 'Bósnia-Herzegóvina',
            'BWA' => 'Botsuana',
            'BRN' => 'Brunei',
            'BGR' => 'Bulgária',
            'BFA' => 'Burkina Fasso',
            'BDI' => 'Burundi',
            'BTN' => 'Butão',
            'CPV' => 'Cabo Verde',
            'CMR' => 'Camarões',
            'KHM' => 'Camboja',
            'CAN' => 'Canadá',
            'KAZ' => 'Cazaquistão',
            'TCD' => 'Chade',
            'CHL' => 'Chile',
            'CHN' => 'China',
            'CYP' => 'Chipre',
            'SGP' => 'Cingapura',
            'COL' => 'Colômbia',
            'COG' => 'Congo',
            'PRK' => 'Coréia do Norte',
            'KOR' => 'Coréia do Sul',
            'CIV' => 'Costa do Marfim',
            'CRI' => 'Costa Rica',
            'HRV' => 'Croácia (Hrvatska)',
            'CUB' => 'Cuba',
            'DNK' => 'Dinamarca',
            'DJI' => 'Djibuti',
            'DMA' => 'Dominica',
            'EGY' => 'Egito',
            'SLV' => 'El Salvador',
            'ARE' => 'Emirados Árabes Unidos',
            'ECU' => 'Equador',
            'ERI' => 'Eritréia',
            'SVK' => 'Eslováquia',
            'SVN' => 'Eslovênia',
            'ESP' => 'Espanha',
            'EST' => 'Estônia',
            'ETH' => 'Etiópia',
            'FJI' => 'Fiji',
            'PHL' => 'Filipinas',
            'FIN' => 'Finlândia',
            'FRA' => 'França',
            'GAB' => 'Gabão',
            'GMB' => 'Gâmbia',
            'GHA' => 'Gana',
            'GEO' => 'Geórgia',
            'GIB' => 'Gibraltar',
            'GBR' => 'Grã-Bretanha (Reino Unido, UK)',
            'GRD' => 'Granada',
            'GRC' => 'Grécia',
            'GRL' => 'Groelândia',
            'GLP' => 'Guadalupe',
            'GUM' => 'Guam (Território dos Estados Unidos)',
            'GTM' => 'Guatemala',
            'GGY' => 'Guernsey',
            'GUY' => 'Guiana',
            'GUF' => 'Guiana Francesa',
            'GIN' => 'Guiné',
            'GNQ' => 'Guiné Equatorial',
            'GNB' => 'Guiné-Bissau',
            'HTI' => 'Haiti',
            'NLD' => 'Holanda',
            'HND' => 'Honduras',
            'HKG' => 'Hong Kong',
            'HUN' => 'Hungria',
            'YEM' => 'Iêmen',
            'BVT' => 'Ilha Bouvet (Território da Noruega)',
            'IMN' => 'Ilha do Homem',
            'CXR' => 'Ilha Natal',
            'PCN' => 'Ilha Pitcairn',
            'REU' => 'Ilha Reunião',
            'ALA' => 'Ilhas Aland',
            'CYM' => 'Ilhas Cayman',
            'CCK' => 'Ilhas Cocos',
            'COM' => 'Ilhas Comores',
            'FRO' => 'Ilhas Faroes',
            'FLK' => 'Ilhas Falkland (Malvinas)',
            'SGS' => 'Ilhas Geórgia do Sul e Sandwich do Sul',
            'HMD' => 'Ilhas Heard e McDonald (Território da Austrália)',
            'MNP' => 'Ilhas Marianas do Norte',
            'MHL' => 'Ilhas Marshall',
            'UMI' => 'Ilhas Menores dos Estados Unidos',
            'NFK' => 'Ilhas Norfolk',
            'SYC' => 'Ilhas Seychelles',
            'SLB' => 'Ilhas Solomão',
            'SJM' => 'Ilhas Svalbard e Jan Mayen',
            'TKL' => 'Ilhas Tokelau',
            'TCA' => 'Ilhas Turks e Caicos',
            'VIR' => 'Ilhas Virgens (Estados Unidos)',
            'VGB' => 'Ilhas Virgens (Inglaterra)',
            'WLF' => 'Ilhas Wallis e Futuna',
            'IND' => 'índia',
            'IDN' => 'Indonésia',
            'IRN' => 'Irã',
            'IRQ' => 'Iraque',
            'IRL' => 'Irlanda',
            'ISL' => 'Islândia',
            'ISR' => 'Israel',
            'ITA' => 'Itália',
            'JAM' => 'Jamaica',
            'JPN' => 'Japão',
            'JEY' => 'Jersey',
            'JOR' => 'Jordânia',
            'KEN' => 'Kênia',
            'KIR' => 'Kiribati',
            'KWT' => 'Kuait',
            'LAO' => 'Laos',
            'LVA' => 'Látvia',
            'LSO' => 'Lesoto',
            'LBN' => 'Líbano',
            'LBR' => 'Libéria',
            'LBY' => 'Líbia',
            'LIE' => 'Liechtenstein',
            'LTU' => 'Lituânia',
            'LUX' => 'Luxemburgo',
            'MAC' => 'Macau',
            'MKD' => 'Macedônia (República Yugoslava)',
            'MDG' => 'Madagascar',
            'MYS' => 'Malásia',
            'MWI' => 'Malaui',
            'MDV' => 'Maldivas',
            'MLI' => 'Mali',
            'MLT' => 'Malta',
            'MAR' => 'Marrocos',
            'MTQ' => 'Martinica',
            'MUS' => 'Maurício',
            'MRT' => 'Mauritânia',
            'MYT' => 'Mayotte',
            'MEX' => 'México',
            'FSM' => 'Micronésia',
            'MOZ' => 'Moçambique',
            'MDA' => 'Moldova',
            'MCO' => 'Mônaco',
            'MNG' => 'Mongólia',
            'MNE' => 'Montenegro',
            'MSR' => 'Montserrat',
            'MMR' => 'Myanma',
            'NAM' => 'Namíbia',
            'NRU' => 'Nauru',
            'NPL' => 'Nepal',
            'NIC' => 'Nicarágua',
            'NER' => 'Níger',
            'NGA' => 'Nigéria',
            'NIU' => 'Niue',
            'NOR' => 'Noruega',
            'NCL' => 'Nova Caledônia',
            'OMN' => 'Nova Zelândia',
            'PLW' => 'Palau',
            'PAN' => 'Panamá',
            'PNG' => 'Papua-Nova Guiné',
            'PAK' => 'Paquistão',
            'PRY' => 'Paraguai',
            'PER' => 'Peru',
            'PYF' => 'Polinésia Francesa',
            'POL' => 'Polônia',
            'PRI' => 'Porto Rico',
            'QAT' => 'Qatar',
            'KGZ' => 'Quirguistão',
            'CAF' => 'República Centro-Africana',
            'COD' => 'República Democrática do Congo',
            'DOM' => 'República Dominicana',
            'CZE' => 'República Tcheca',
            'ROM' => 'Romênia',
            'RWA' => 'Ruanda',
            'RUS' => 'Rússia',
            'ESH' => 'Saara Ocidental',
            'VCT' => 'Saint Vincente e Granadinas',
            'ASM' => 'Samoa Americana',
            'WSM' => 'Samoa Ocidental',
            'SMR' => 'San Marino',
            'SHN' => 'Santa Helena',
            'LCA' => 'Santa Lúcia',
            'BLM' => 'São Bartolomeu',
            'KNA' => 'São Cristóvão e Névis',
            'MAF' => 'São Martim',
            'STP' => 'São Tomé e Príncipe',
            'SEN' => 'Senegal',
            'SLE' => 'Serra Leoa',
            'SRB' => 'Sérvia',
            'SYR' => 'Síria',
            'SOM' => 'Somália',
            'LKA' => 'Sri Lanka',
            'SPM' => 'St. Pierre and Miquelon',
            'SWZ' => 'Suazilândia',
            'SDN' => 'Sudão',
            'SWE' => 'Suécia',
            'CHE' => 'Suíça',
            'SUR' => 'Suriname',
            'TJK' => 'Tadjiquistão',
            'THA' => 'Tailândia',
            'TWN' => 'Taiwan',
            'TZA' => 'Tanzânia',
            'IOT' => 'Território Britânico do Oceano índico',
            'ATF' => 'Territórios do Sul da França',
            'PSE' => 'Territórios Palestinos Ocupados',
            'TMP' => 'Timor Leste',
            'TGO' => 'Togo',
            'TON' => 'Tonga',
            'TTO' => 'Trinidad and Tobago',
            'TUN' => 'Tunísia',
            'TKM' => 'Turcomenistão',
            'TUR' => 'Turquia',
            'TUV' => 'Tuvalu',
            'UKR' => 'Ucrânia',
            'UGA' => 'Uganda',
            'URY' => 'Uruguai',
            'UZB' => 'Uzbequistão',
            'VUT' => 'Vanuatu',
            'VAT' => 'Vaticano',
            'VEN' => 'Venezuela',
            'VNM' => 'Vietnã',
            'ZMB' => 'Zâmbia',
            'ZWE' => 'Zimbábue',
        ];
    }

    private function converCountryCode()
    {
        return array(
            "AF" => "AFG",
            "AL" => "ALB",
            "DZ" => "DZA",
            "AS" => "ASM",
            "AD" => "AND",
            "AO" => "AGO",
            "AI" => "AIA",
            "AQ" => "ATA",
            "AG" => "ATG",
            "AR" => "ARG",
            "AM" => "ARM",
            "AW" => "ABW",
            "AU" => "AUS",
            "AT" => "AUT",
            "AZ" => "AZE",
            "BS" => "BHS",
            "BH" => "BHR",
            "BD" => "BGD",
            "BB" => "BRB",
            "BY" => "BLR",
            "BE" => "BEL",
            "BZ" => "BLZ",
            "BJ" => "BEN",
            "BM" => "BMU",
            "BT" => "BTN",
            "BO" => "BOL",
            "BQ" => "BES",
            "BA" => "BIH",
            "BW" => "BWA",
            "BV" => "BVT",
            "BR" => "BRA",
            "IO" => "IOT",
            "BN" => "BRN",
            "BG" => "BGR",
            "BF" => "BFA",
            "BI" => "BDI",
            "CV" => "CPV",
            "KH" => "KHM",
            "CM" => "CMR",
            "CA" => "CAN",
            "KY" => "CYM",
            "CF" => "CAF",
            "TD" => "TCD",
            "CL" => "CHL",
            "CN" => "CHN",
            "CX" => "CXR",
            "CC" => "CCK",
            "CO" => "COL",
            "KM" => "COM",
            "CD" => "COD",
            "CG" => "COG",
            "CK" => "COK",
            "CR" => "CRI",
            "HR" => "HRV",
            "CU" => "CUB",
            "CW" => "CUW",
            "CY" => "CYP",
            "CZ" => "CZE",
            "CI" => "CIV",
            "DK" => "DNK",
            "DJ" => "DJI",
            "DM" => "DMA",
            "DO" => "DOM",
            "EC" => "ECU",
            "EG" => "EGY",
            "SV" => "SLV",
            "GQ" => "GNQ",
            "ER" => "ERI",
            "EE" => "EST",
            "SZ" => "SWZ",
            "ET" => "ETH",
            "FK" => "FLK",
            "FO" => "FRO",
            "FJ" => "FJI",
            "FI" => "FIN",
            "FR" => "FRA",
            "GF" => "GUF",
            "PF" => "PYF",
            "TF" => "ATF",
            "GA" => "GAB",
            "GM" => "GMB",
            "GE" => "GEO",
            "DE" => "DEU",
            "GH" => "GHA",
            "GI" => "GIB",
            "GR" => "GRC",
            "GL" => "GRL",
            "GD" => "GRD",
            "GP" => "GLP",
            "GU" => "GUM",
            "GT" => "GTM",
            "GG" => "GGY",
            "GN" => "GIN",
            "GW" => "GNB",
            "GY" => "GUY",
            "HT" => "HTI",
            "HM" => "HMD",
            "VA" => "VAT",
            "HN" => "HND",
            "HK" => "HKG",
            "HU" => "HUN",
            "IS" => "ISL",
            "IN" => "IND",
            "ID" => "IDN",
            "IR" => "IRN",
            "IQ" => "IRQ",
            "IE" => "IRL",
            "IM" => "IMN",
            "IL" => "ISR",
            "IT" => "ITA",
            "JM" => "JAM",
            "JP" => "JPN",
            "JE" => "JEY",
            "JO" => "JOR",
            "KZ" => "KAZ",
            "KE" => "KEN",
            "KI" => "KIR",
            "KP" => "PRK",
            "KR" => "KOR",
            "KW" => "KWT",
            "KG" => "KGZ",
            "LA" => "LAO",
            "LV" => "LVA",
            "LB" => "LBN",
            "LS" => "LSO",
            "LR" => "LBR",
            "LY" => "LBY",
            "LI" => "LIE",
            "LT" => "LTU",
            "LU" => "LUX",
            "MO" => "MAC",
            "MG" => "MDG",
            "MW" => "MWI",
            "MY" => "MYS",
            "MV" => "MDV",
            "ML" => "MLI",
            "MT" => "MLT",
            "MH" => "MHL",
            "MQ" => "MTQ",
            "MR" => "MRT",
            "MU" => "MUS",
            "YT" => "MYT",
            "MX" => "MEX",
            "FM" => "FSM",
            "MD" => "MDA",
            "MC" => "MCO",
            "MN" => "MNG",
            "ME" => "MNE",
            "MS" => "MSR",
            "MA" => "MAR",
            "MZ" => "MOZ",
            "MM" => "MMR",
            "NA" => "NAM",
            "NR" => "NRU",
            "NP" => "NPL",
            "NL" => "NLD",
            "NC" => "NCL",
            "NZ" => "NZL",
            "NI" => "NIC",
            "NE" => "NER",
            "NG" => "NGA",
            "NU" => "NIU",
            "NF" => "NFK",
            "MP" => "MNP",
            "NO" => "NOR",
            "OM" => "OMN",
            "PK" => "PAK",
            "PW" => "PLW",
            "PS" => "PSE",
            "PA" => "PAN",
            "PG" => "PNG",
            "PY" => "PRY",
            "PE" => "PER",
            "PH" => "PHL",
            "PN" => "PCN",
            "PL" => "POL",
            "PT" => "PRT",
            "PR" => "PRI",
            "QA" => "QAT",
            "MK" => "MKD",
            "RO" => "ROU",
            "RU" => "RUS",
            "RW" => "RWA",
            "RE" => "REU",
            "BL" => "BLM",
            "SH" => "SHN",
            "KN" => "KNA",
            "LC" => "LCA",
            "MF" => "MAF",
            "PM" => "SPM",
            "VC" => "VCT",
            "WS" => "WSM",
            "SM" => "SMR",
            "ST" => "STP",
            "SA" => "SAU",
            "SN" => "SEN",
            "RS" => "SRB",
            "SC" => "SYC",
            "SL" => "SLE",
            "SG" => "SGP",
            "SX" => "SXM",
            "SK" => "SVK",
            "SI" => "SVN",
            "SB" => "SLB",
            "SO" => "SOM",
            "ZA" => "ZAF",
            "GS" => "SGS",
            "SS" => "SSD",
            "ES" => "ESP",
            "LK" => "LKA",
            "SD" => "SDN",
            "SR" => "SUR",
            "SJ" => "SJM",
            "SE" => "SWE",
            "CH" => "CHE",
            "SY" => "SYR",
            "TW" => "TWN",
            "TJ" => "TJK",
            "TZ" => "TZA",
            "TH" => "THA",
            "TL" => "TLS",
            "TG" => "TGO",
            "TK" => "TKL",
            "TO" => "TON",
            "TT" => "TTO",
            "TN" => "TUN",
            "TR" => "TUR",
            "TM" => "TKM",
            "TC" => "TCA",
            "TV" => "TUV",
            "UG" => "UGA",
            "UA" => "UKR",
            "AE" => "ARE",
            "GB" => "GBR",
            "UM" => "UMI",
            "US" => "USA",
            "UY" => "URY",
            "UZ" => "UZB",
            "VU" => "VUT",
            "VE" => "VEN",
            "VN" => "VNM",
            "VG" => "VGB",
            "VI" => "VIR",
            "WF" => "WLF",
            "EH" => "ESH",
            "YE" => "YEM",
            "ZM" => "ZMB",
            "ZW" => "ZWE",
            "AX" => "ALA"
        );

    }

}
